# Generated by Django 3.1.7 on 2021-04-03 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_activity_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='value',
        ),
        migrations.AddField(
            model_name='activity',
            name='new_Value',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='activity',
            name='old_value',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
